import 'package:flutter/material.dart';
import '../../../shared/orbit_live_colors.dart';
import 'driver_dashboard.dart';

/// Screen for entering custom vehicle ID (optional - for manual override)
class VehicleIdInputScreen extends StatefulWidget {
  const VehicleIdInputScreen({super.key});

  @override
  State<VehicleIdInputScreen> createState() => _VehicleIdInputScreenState();
}

class _VehicleIdInputScreenState extends State<VehicleIdInputScreen> {
  final TextEditingController _vehicleIdController = TextEditingController();
  final TextEditingController _driverIdController = TextEditingController();
  bool _useAutoGenerated = true;

  @override
  void initState() {
    super.initState();
    // Generate default IDs
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final deviceHash = timestamp.hashCode.abs().toString().substring(0, 4);
    _vehicleIdController.text = 'BUS-$deviceHash-${timestamp.toString().substring(8)}';
    _driverIdController.text = 'DRIVER-$deviceHash';
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: OrbitLiveColors.primaryBlue,
      appBar: AppBar(
        title: const Text('Vehicle Setup'),
        backgroundColor: Colors.transparent,
        elevation: 0,
        foregroundColor: Colors.white,
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(24.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Header
              const Text(
                'Vehicle Configuration',
                style: TextStyle(
                  fontSize: 28,
                  fontWeight: FontWeight.bold,
                  color: Colors.white,
                ),
              ),
              
              const SizedBox(height: 8),
              
              Text(
                'Each device needs a unique vehicle ID for live tracking',
                style: TextStyle(
                  fontSize: 16,
                  color: Colors.white.withOpacity(0.8),
                ),
              ),
              
              const SizedBox(height: 32),
              
              // Auto-generated toggle
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: Colors.white.withOpacity(0.1),
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(
                    color: Colors.white.withOpacity(0.2),
                  ),
                ),
                child: Row(
                  children: [
                    Icon(
                      _useAutoGenerated ? Icons.auto_awesome : Icons.edit,
                      color: Colors.white,
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            _useAutoGenerated ? 'Auto-Generated IDs' : 'Custom IDs',
                            style: const TextStyle(
                              color: Colors.white,
                              fontSize: 16,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                          Text(
                            _useAutoGenerated 
                                ? 'Unique IDs generated automatically'
                                : 'Enter your own vehicle and driver IDs',
                            style: TextStyle(
                              color: Colors.white.withOpacity(0.7),
                              fontSize: 14,
                            ),
                          ),
                        ],
                      ),
                    ),
                    Switch(
                      value: _useAutoGenerated,
                      onChanged: (value) {
                        setState(() {
                          _useAutoGenerated = value;
                        });
                      },
                      activeColor: Colors.white,
                      activeTrackColor: Colors.white.withOpacity(0.3),
                    ),
                  ],
                ),
              ),
              
              const SizedBox(height: 24),
              
              // Vehicle ID Input
              _buildInputField(
                controller: _vehicleIdController,
                label: 'Vehicle ID',
                hint: 'e.g., BUS-1234-567890',
                icon: Icons.directions_bus,
                enabled: !_useAutoGenerated,
              ),
              
              const SizedBox(height: 16),
              
              // Driver ID Input
              _buildInputField(
                controller: _driverIdController,
                label: 'Driver ID',
                hint: 'e.g., DRIVER-1234',
                icon: Icons.person,
                enabled: !_useAutoGenerated,
              ),
              
              const Spacer(),
              
              // Info box
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: Colors.orange.withOpacity(0.2),
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(
                    color: Colors.orange.withOpacity(0.3),
                  ),
                ),
                child: Row(
                  children: [
                    const Icon(
                      Icons.info_outline,
                      color: Colors.orange,
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Text(
                        'Multiple devices can run simultaneously. Each will appear as a separate bus on the admin dashboard.',
                        style: TextStyle(
                          color: Colors.white.withOpacity(0.9),
                          fontSize: 14,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              
              const SizedBox(height: 24),
              
              // Start Button
              SizedBox(
                width: double.infinity,
                height: 56,
                child: ElevatedButton.icon(
                  onPressed: () {
                    if (_vehicleIdController.text.trim().isEmpty) {
                      ScaffoldMessenger.of(context).showSnackBar(
                        const SnackBar(
                          content: Text('Please enter a vehicle ID'),
                          backgroundColor: Colors.red,
                        ),
                      );
                      return;
                    }
                    
                    Navigator.pushReplacement(
                      context,
                      MaterialPageRoute(
                        builder: (context) => DriverDashboard(
                          customVehicleId: _vehicleIdController.text.trim(),
                          customDriverId: _driverIdController.text.trim(),
                        ),
                      ),
                    );
                  },
                  icon: const Icon(Icons.play_arrow),
                  label: const Text(
                    'Start Driver Dashboard',
                    style: TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.white,
                    foregroundColor: OrbitLiveColors.primaryBlue,
                    elevation: 8,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(16),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildInputField({
    required TextEditingController controller,
    required String label,
    required String hint,
    required IconData icon,
    bool enabled = true,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: const TextStyle(
            color: Colors.white,
            fontSize: 16,
            fontWeight: FontWeight.w600,
          ),
        ),
        const SizedBox(height: 8),
        TextFormField(
          controller: controller,
          enabled: enabled,
          style: TextStyle(
            color: enabled ? Colors.black : Colors.grey[600],
            fontSize: 16,
          ),
          decoration: InputDecoration(
            hintText: hint,
            hintStyle: TextStyle(color: Colors.grey[500]),
            prefixIcon: Icon(icon, color: Colors.grey[600]),
            filled: true,
            fillColor: enabled ? Colors.white : Colors.grey[200],
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide.none,
            ),
            contentPadding: const EdgeInsets.symmetric(
              horizontal: 16,
              vertical: 16,
            ),
          ),
        ),
      ],
    );
  }

  @override
  void dispose() {
    _vehicleIdController.dispose();
    _driverIdController.dispose();
    super.dispose();
  }
}