// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9EBdqnsV8xIzCHngH8O0Ca-_KaoUu9z4',
    appId: '1:423535385058:web:eb6cde3a491bfb197f81bb',
    messagingSenderId: '423535385058',
    projectId: 'orbit-live-3836f',
    authDomain: 'orbit-live-3836f.firebaseapp.com',
    databaseURL: 'https://orbit-live-3836f-default-rtdb.firebaseio.com',
    storageBucket: 'orbit-live-3836f.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEktAlfKsSpJny92ON2W5jzP7cjUmi4Qs',
    appId: '1:423535385058:android:655b667ca3ae19c57f81bb',
    messagingSenderId: '423535385058',
    projectId: 'orbit-live-3836f',
    databaseURL: 'https://orbit-live-3836f-default-rtdb.firebaseio.com',
    storageBucket: 'orbit-live-3836f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEktAlfKsSpJny92ON2W5jzP7cjUmi4Qs',
    appId: '1:423535385058:ios:655b667ca3ae19c57f81bb',
    messagingSenderId: '423535385058',
    projectId: 'orbit-live-3836f',
    databaseURL: 'https://orbit-live-3836f-default-rtdb.firebaseio.com',
    storageBucket: 'orbit-live-3836f.firebasestorage.app',
    iosBundleId: 'com.example.publicTransportTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEktAlfKsSpJny92ON2W5jzP7cjUmi4Qs',
    appId: '1:423535385058:ios:655b667ca3ae19c57f81bb',
    messagingSenderId: '423535385058',
    projectId: 'orbit-live-3836f',
    databaseURL: 'https://orbit-live-3836f-default-rtdb.firebaseio.com',
    storageBucket: 'orbit-live-3836f.firebasestorage.app',
    iosBundleId: 'com.example.publicTransportTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9EBdqnsV8xIzCHngH8O0Ca-_KaoUu9z4',
    appId: '1:423535385058:web:eb6cde3a491bfb197f81bb',
    messagingSenderId: '423535385058',
    projectId: 'orbit-live-3836f',
    authDomain: 'orbit-live-3836f.firebaseapp.com',
    databaseURL: 'https://orbit-live-3836f-default-rtdb.firebaseio.com',
    storageBucket: 'orbit-live-3836f.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
}